# storing API data

key = "LWB8PQKGrMXGIZcYF3spFdJCC"
key_secret = "IFiC9cLk3kXyJPqHp9FBU4QwRnx5ATUZVHHGNXaKjaInP5K8B7"
bearer_token = "AAAAAAAAAAAAAAAAAAAAADWAVAEAAAAA%2F56g2zn0JqukNsQ%2Fn83lLXn4zWQ%3DuWjmqchGKwHZTsokPKVPr0nWEzFvoIaJ53wMtZOXhJkqNh8jBK"